---
version: "3"
services:

  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:arm64v8-latest
    ports:
      - 8443:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - PASSWORD=raspberry
      - HASHED_PASSWORD=
      - SUDO_PASSWORD=raspberry
      - SUDO_PASSWORD_HASH=
      - PROXY_DOMAIN=raspberry.fritz.box
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /opt/code-server:/config
    restart: unless-stopped

  homebridge:
    container_name: homebridge
    image: oznu/homebridge:ubuntu
    ports:
      - 8581:8581
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Europe/Vienna
    volumes:
      - /opt/homebridge:/homebridge
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      - TZ=America/Chicago
      - WEBPASSWORD=raspberry
    volumes:
      - /opt/pihole/etc-pihole:/etc/pihole
      - /opt/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

  ubuntu:
    container_name: ubuntu
    image: ubuntu:focal
